export const SEARCHBOX_DISABLE_BUTTON = 'SEARCHBOX/DISABLED_BUTTON'
export const SEARCHBOX_ITEM_SELECTED = 'SEARCHBOX/ITEM_SELECTED'
export const SEARCHBOX_TEXT = 'SEARCHBOX/TEXTBOX'

export const RESULT_TABLE_GOOGLE_FETCH_IMAGES = 'RESULT_TABLE/GOOGLE/FETCH_IMAGES'
export const RESULT_TABLE_BING_FETCH_IMAGES = 'RESULT_TABLE/BING/FETCH_IMAGES'
export const RESULT_TABLE_IS_SEARCHING = 'RESULT_TABLE/IS_SEARCHING'
